name: hermit_home
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.2
  mongo_dart: ^0.9.1
  animate_do: ^3.3.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Avatar_Hhome.jpg" # Sửa "asstes" thành "assets"